[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
no_implicit_optional = true

[[tool.mypy.overrides]]
disallow_untyped_defs = false
module = ["testing.*", "tests.*"]

[tool.ruff]
target-version = "py38"

[tool.ruff.lint]
extend-select = [
  "UP",  # see pyupgrade
  "B",  # see flake8-bugbear
  "A",  # see flake8-builtins
  "C4",  # see flake8-comprehension
  "SIM",  # see flake8-simplify
  "TCH"  # see flake8-type-checking
]
